context.properties = {
    core.name = pipewire-0
    default.clock.rate = 48000
    default.clock.min-quantum = 1024
    module.jackdbus-detect = false
    module.x11.bell = false
}
context.modules = [
    { name = libpipewire-module-loopback
      args = {
        audio.rate = 48000
        audio.channels = 1
        audio.position = [ MONO ]
        capture.props = {
            node.name = elsewhere-microphone-input
            node.description = "Elsewhere microphone input"
            media.class = Audio/Sink
            node.virtual = true
            priority.session = 1
        }
        playback.props = {
            node.name = elsewhere-microphone
            node.always-process = true
            node.description = "Elsewhere microphone"
            media.class = Audio/Source
            node.virtual = true
            priority.session = 3000
        }
      }
    }
]
context.objects = [
    { factory = adapter
      args = {
        factory.name = support.null-audio-sink
        node.name = elsewhere-output
        node.always-process = true
        monitor.channel-volumes = true
        node.description = "Elsewhere audio"
        media.class = Audio/Sink
        node.virtual = true
        audio.position = [ FL FR ]
        priority.session = 2000
      }
    }
]
