wireplumber.profiles = {
    elsewhere = {
        inherits = [ policy, mixin.systemwide-session, mixin.stateless ]
        hardware.audio = disabled
        hardware.bluetooth = disabled
        hardware.video-capture = disabled
        support.dbus = disabled
    }
}
