context.properties = {
    link.max-buffers = 16
    core.daemon = true
    core.name = pipewire-0
    default.clock.rate = 48000
}
context.spa-libs = {
    audio.convert.* = audioconvert/libspa-audioconvert
    support.* = support/libspa-support
}
context.modules = [
    { name = libpipewire-module-protocol-native }
    { name = libpipewire-module-metadata }
    { name = libpipewire-module-spa-node-factory }
    { name = libpipewire-module-client-node }
    { name = libpipewire-module-client-device }
    { name = libpipewire-module-access }
    { name = libpipewire-module-adapter }
    { name = libpipewire-module-link-factory }
    { name = libpipewire-module-session-manager }
    { name = libpipewire-module-loopback
      args = {
        audio.rate = 48000
        audio.channels = 1
        audio.position = [ MONO ]
        capture.props = {
            node.name = browser-wayland-microphone-input
            node.description = "Browser microphone input"
            media.class = Audio/Sink
            node.virtual = true
            priority.session = 1
        }
        playback.props = {
            node.name = browser-wayland-microphone
            node.always-process = true
            node.description = "Browser microphone"
            media.class = Audio/Source
            node.virtual = true
            priority.session = 3000
        }
      }
    }
]
context.objects = [
    { factory = spa-node-factory
      args = {
        factory.name = support.node.driver
        node.name = Dummy-Driver
        node.group = pipewire.dummy
        priority.driver = 200000
      }
    }
    { factory = adapter
      args = {
        factory.name = support.null-audio-sink
        node.name = browser-wayland-output
        node.always-process = true
        monitor.channel-volumes = true
        node.description = "Browser audio"
        media.class = Audio/Sink
        node.virtual = true
        audio.position = [ FL FR ]
        priority.session = 2000
      }
    }
]
